### PR TITLE
refactor: improve generate function structure

### PR DESCRIPTION
**Pull request by thebedigupta**
**Description**
In this PR I resolved this [issue](https://sonarcloud.io/project/issuesopen=AZB4sejAgviDxNeZYbKR&id=asyncapi_generator) 
Forget to attach test results file [test-results.txt](https://github.com/user-attachments/files/17262915/test-results.txt)

**The Issue**
The original code used an async function directly in the Promise constructor.

**The Solution**
I've updated the code to wrap the async logic in an immediately invoked async function within the Promise executor.
I am also attching test-results file to get better know what tests I performed

**Related issue(s)**

### CODE REVIEW

**Review by Gmin2 — COMMENTED** [review]
remove all the formating change done in the PR !

**Comment by thebedigupta** [comment]
> remove all the formating change done in the PR !

Done thank you for your understanding and sorry for my misake

**Comment by derberg** [comment]
@thebedigupta please provide again a link to sonarcloud as the one you have in description do not point to any specific issue

**Comment by thebedigupta** [comment]
> @thebedigupta please provide again a link to sonarcloud as the one you have in description do not point to any specific issue

https://sonarcloud.io/project/issues?open=AZB4sejAgviDxNeZYbKR&id=asyncapi_generator

**Review by derberg — COMMENTED** [review]
usage of iffe is not a correct solution

better would be to really just remove promise from the code and make function async.

anyway, doesn't make sense to waste your time on code in `cli.js` as it is a code that we wanna remove entirely and do not want to invest in it

I'll close that PR, feel free to work on something not related to `cli.js`

**Pull request closed without merging**
