### PR TITLE
chore: add `next-major` branch to release list

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This PR adds the `next-major` branch to the release list.

**Related issue(s)**
Related to spec 3.0 https://github.com/asyncapi/spec/issues/691

### CODE REVIEW

**Comment by jonaslagoni** [comment]
We also need to add branch protection to `next-major`.

**Review by derberg — APPROVED** [review]
I created branch protection for you for the new release branch

**Comment by derberg** [comment]
@jonaslagoni  It would make sense to open up a PR from `next-major` to `master` with `don-not-merge` label. This way bot will make sure to always update release branch with latest master....if possible of course. Anyway release branch requires an update as there are some missing workflows that will not work with branch protection

**Comment by jonaslagoni** [comment]
> @jonaslagoni It would make sense to open up a PR from `next-major` to `master` with `don-not-merge` label. This way bot will make sure to always update release branch with latest master....if possible of course. Anyway release branch requires an update as there are some missing workflows that will not work with branch protection

Yes, will do that 👍

**Comment by derberg** [comment]
closed/reopened as some jobs were "hanging"
@jonaslagoni once it is green merge when you need it

**Comment by jonaslagoni** [comment]
@derberg had to update with master for checks to go through 😅

**Review by derberg — APPROVED** [review]

**Pull request merged**
