### PR TITLE
docs: add java-template to list

### PR DESCRIPTION
**Pull request by dan-r**
Hi all and thank you for the warm welcome to the AsyncAPI community!
This PR is just to add the java-template to the list as we've recently moved it to the asyncapi organisation.

### CODE REVIEW

**Review by derberg — COMMENTED** [review]
lgtm, but we need to wait once it is actually released to npm

**Comment by dan-r** [comment]
@derberg released to NPM now!

**Comment by derberg** [comment]
awesome! can I use you and could you add https://github.com/asyncapi/go-watermill-template too 😅

**Comment by derberg** [comment]
Thanks so much!
I also added proper topics to your repo so it gets visible [here](https://github.com/search?q=topic%3Aasyncapi+topic%3Agenerator+topic%3Atemplate) too

**Review by derberg — APPROVED** [review]

**Pull request merged**
