### PR TITLE
chore: update the readme file path for docker hub

### PR DESCRIPTION
**Pull request by ayushnau**
Changes Added.

1.  updated the readme file path in the ci.

Related issue(s)

Related to: https://github.com/asyncapi/generator/issues/1044

### CODE REVIEW

**Review by derberg — APPROVED** [review]
@ayushnau I removed a changeset as we do not have to make a release in that case, as the bug is not code artifact related, docker publishing worked, just readme was not pushed to dockerhub

**Comment by aeworxet** [comment]
@asyncapi/bounty_team

**Pull request merged**
