### PR TITLE
chore: add chromium to docker for html-template

### PR DESCRIPTION
**Pull request by derberg**
**Description**

- add chromium to docker for html-template

**Related issue(s)**
Fixes https://github.com/asyncapi/html-template/issues/112

### CODE REVIEW

**Review by jonaslagoni — COMMENTED** [review]
@derberg is it not possible to get around adding a global package to the dockerfile to accommodate 1 template? It seems... Wrong 😄

**Comment by derberg** [comment]
@jonaslagoni yeah, I know what you mean, but there is no other way really. At the end, html-template is an official template, so I do not see this as a big problem.

**Comment by jonaslagoni** [comment]
> @jonaslagoni yeah, I know what you mean, but there is no other way really. At the end, html-template is an official template, so I do not see this as a big problem.

Can't we imagine this is something everyone could benefit from, adding a feature which controls the docker environment per template? I can understand if we just want to make this a temporary fix, however there should be an issue where this is raised IMO.

**Comment by derberg** [comment]
@jonaslagoni tbh I have no idea how else this could be solved, other than saying `create your own image using generator image as a base`. I also cannot really imagine any other template needing such a custom approach. Puppeteer is just unique here needing dedicated chromium instance for alpine. What I'm trying to say is that any followup issue will just be food for the stale bot 😄 as we do not have a use case for such extensibility. Maybe I add a comment that in case more customizations are needed for other templates, we should consider reworking the image?

**Comment by jonaslagoni** [comment]
> What I'm trying to say is that any followup issue will just be food for the stale bot 😄 as we do not have a use case for such extensibility. Maybe I add a comment that in case more customizations are needed for other templates, we should consider reworking the image?

I mean, you just had the use case 😄 If 1 template requires custom dependencies, others will probably too, even if we can't think of a reason atm. I mean there are different methods to make it require dependencies, extending the generator docker image, make a framework for shell files, **make** files etc. But I agree atm this is too much, but I still think an issue would be valid. Ill accept the PR on the notion that this is temporary 😄

**Review by jonaslagoni — APPROVED** [review]
see comment.

**Comment by derberg** [comment]
@jonaslagoni yo, can you approve again, I added a comment to dockerfile

**Review by jonaslagoni — APPROVED** [review]

**Pull request merged**
