### PR TITLE
fix: remove deprecated import

### LINKED ISSUE #770: simple-git/promise import warning
#### Describe the bug
While using the generator to generate html doc , a warning from simple-git is raised : 

`
=============================================
simple-git has supported promises / async await since version 2.6.0.
 Importing from 'simple-git/promise' has been deprecated and will be
 removed by July 2022.

To upgrade, change all 'simple-git/promise' imports to just 'simple-git'
=============================================
`

#### How to Reproduce
used generator version : 1.9.1
Just try to generate html doc from an asyncapi.yaml.
`
npx ag specs/asyncapi.yaml ../node_modules/@asyncapi/html-template -o ./html
`

#### Expected behavior
No warning from simple-git

### PR DESCRIPTION
**Pull request by pavlikm**
Resolves #770

### CODE REVIEW

**Comment by magicmatatjahu** [comment]
@pavlikm Hello! Thanks for contribution! Please follow by PR title rules: https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md#conventional-commits

**Comment by pavlikm** [comment]
@derberg it is based on error showed on start of application using this generator:
```
=============================================
simple-git has supported promises / async await since version 2.6.0.
 Importing from 'simple-git/promise' has been deprecated and will be
 removed by July 2022.

To upgrade, change all 'simple-git/promise' imports to just 'simple-git'
=============================================

```

**Comment by derberg** [comment]
@pavlikm I'm not questioning if it is needed, just want to make sure it still works 😄 just run generation on local and point output to folder with `.git` directory and confirm you get a proper error message

**Comment by pavlikm** [comment]
@derberg yes, if it should show me error about unstaged changes, then it works well:
```
C:\Users\pavlik\Documents\workspace\platform\message-service>ag -o . async.json https://github.com/asyncapi/html-template
Something went wrong:
Error: "C:\Users\pavlik\Documents\workspace\platform\message-service" is in a git repository with unstaged changes. Please commit your changes before proceeding or add proper directory to .gitignore file. You can also use the --forc
e-write flag to skip this rule (not recommended).
    at Generator.verifyTargetDir (C:\Users\pavlik\AppData\Roaming\npm\node_modules\@asyncapi\generator\lib\generator.js:846:71)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Generator.generate (C:\Users\pavlik\AppData\Roaming\npm\node_modules\@asyncapi\generator\lib\generator.js:173:29)
    at C:\Users\pavlik\AppData\Roaming\npm\node_modules\@asyncapi\generator\cli.js:154:9

```
the only difference against master is, that info pasted in my previous comment is missing

**Review by derberg — APPROVED** [review]
LGTM, @magicmatatjahu anything from you?

**Review by magicmatatjahu — APPROVED** [review]

**Comment by magicmatatjahu** [comment]
@derberg It's ok.

**Pull request merged**
