### PR TITLE
refactor-only; prepare for multiple front-ends, refs #35

### PR DESCRIPTION
**Pull request by MikeRalphson**
This PR does not affect functionality (as far as I can determine), it merely moves files around ready to support multiple front-ends as per #35 and for AsyncAPI v2.

### CODE REVIEW

**Comment by fmvilas** [comment]
> Encrypted environment variables have been removed for security reasons.
> See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

Don't you have permissions to create Pull Requests directly here? I mean, without forking.

**Comment by fmvilas** [comment]
Can you rebase with master and push again? I just fixed the problem.

**Comment by MikeRalphson** [comment]
Will do. Just fork out of habit from other projects.

**Comment by rmelian** [comment]
what's going on here, is this still relevant?

**Comment by MikeRalphson** [comment]
I'd hope so, PR is only a few days old. Rationale is in the description and matches what was discussed in Slack.

**Pull request closed without merging**
