### PR TITLE
docs: update incorrect link

### PR DESCRIPTION
**Pull request by anaysarkar7**
Updated incorrect link 
Issue : [asyncApi/website/Issue-1206](https://github.com/asyncapi/website/issues/1206)

### CODE REVIEW

**Comment by derberg** [comment]
@Florence-Njeri @pratik2315 hey folks, pinging you for review.

I think you were not assigned by default because looking at [docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners), the order in https://github.com/asyncapi/generator/blob/master/CODEOWNERS should be flipped

```
Order is important; the last matching pattern takes the most precedence
```

**Review by Florence-Njeri — APPROVED** [review]

**Comment by Florence-Njeri** [comment]
Let me take a look

**Review by Florence-Njeri — APPROVED** [review]

**Comment by pratik2315** [comment]
> @Florence-Njeri @pratik2315 hey folks, pinging you for review.
> 
> I think you were not assigned by default because looking at [docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners), the order in https://github.com/asyncapi/generator/blob/master/CODEOWNERS should be flipped
> 
> ```
> Order is important; the last matching pattern takes the most precedence
> ```

Hey @derberg. So if I'm correct, the usernames that come after both @Florence-Njeri and @pratik2315 are kinda overwriting our assignments right? So.. the ideal order should be:

```
* @fmvilas @derberg @magicmatatjahu @jonaslagoni @asyncapi-bot-eve 

# All .md files
*.md @Florence-Njeri @pratik2315
```

but wouldn't that restrict you guys from getting docs (markdown) related notifications?

**Comment by derberg** [comment]
> but wouldn't that restrict you guys from getting docs (markdown) related notifications?

@pratik2315 good question. Yes, I think it works this way that you will get notifications first. It kinda makes sense to me, that first you and @Florence-Njeri get notification as you are `md` files maintainers. So basically you do the initial review, and you explicitly ping other maintainers if their review is also needed. So for example in case of link fix (like here) it is enough that you are pinged. Makes sense?

@anaysarkar7 thanks for your patience 🙏🏼 Can you update the PR title to start with `docs: ` and not use past tense? (use[ imperative mood](https://cbea.ms/git-commit/#imperative) please)
@pratik2315 @Florence-Njeri during review please make sure https://github.com/asyncapi/generator/blob/master/CONTRIBUTING.md#conventional-commits is followed. In case of docs, we should not use `fix` or `feat` as this will trigger release

**Comment by anaysarkar7** [comment]
> > but wouldn't that restrict you guys from getting docs (markdown) related notifications?
> 
> @pratik2315 good question. Yes, I think it works this way that you will get notifications first. It kinda makes sense to me, that first you and @Florence-Njeri get notification as you are `md` files maintainers. So basically you do the initial review, and you explicitly ping other maintainers if their review is also needed. So for example in case of link fix (like here) it is enough that you are pinged. Makes sense?
> 
> @anaysarkar7 thanks for your patience 🙏🏼 Can you update the PR title to start with `docs: ` and not use past tense? (use[ imperative mood](https://cbea.ms/git-commit/#imperative) please) @pratik2315 @Florence-Njeri during review please make sure https://github.com/asyncapi/generator/blob/master/CONTRIBUTING.md#conventional-commits is followed. In case of docs, we should not use `fix` or `feat` as this will trigger release

done :)

**Comment by pratik2315** [comment]
LGTM @anaysarkar7 🚀

**Review by pratik2315 — APPROVED** [review]

**Review by derberg — APPROVED** [review]

**Pull request merged**
