### PR TITLE
docs: nodejs spelling correction

### LINKED ISSUE #919: [Docs Bug 🐞 report]: Typo error in docs/template.md file
### Describe the bug you found in AsyncAPI Docs.

It should be node.js instead of nodej.s

### Attach any resources that can help us understand the issue.

image
image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sambhavgupta0705**
**Description**

- corrected the spelling of nodejs in template.md file

**Related issue(s)**

Fixes #919

### CODE REVIEW

**Comment by sambhavgupta0705** [comment]
PTAL @pratik2315

**Comment by pratik2315** [comment]
Awesome work @sambhavgupta0705! Just one minor thing, the `fix:` prefix in the title is meant for bugfixes and hence it triggers patch release. You can just use the usual `docs:` prefix for docs related issues. Check this [section](https://github.com/asyncapi/generator/blob/master/CONTRIBUTING.md#conventional-commits) for more info on that!

**Review by pratik2315 — APPROVED** [review]
LGTM🚀

Heyy @Florence-Njeri any suggestions😄

**Comment by sambhavgupta0705** [comment]
> Awesome work @sambhavgupta0705! Just one minor thing, the `fix:` prefix in the title is meant for bugfixes and hence it triggers patch release. You can just use the usual `docs:` prefix for docs related issues. Check this [section](https://github.com/asyncapi/generator/blob/master/CONTRIBUTING.md#conventional-commits) for more info on that! 

Ok @pratik2315 ,will take care of this.

**Review by Florence-Njeri — APPROVED** [review]

**Pull request merged**
