### PR TITLE
refactor: switch to optional chaining in custom filters and removing unnecessary escape character in logMessages.js

### PR DESCRIPTION
**Pull request by rishabhr4**
This PR aims to resolve all the issues in logmessages.js . These are the issue 
[issue1](https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&id=asyncapi_generator&open=AZB4sejVgviDxNeZYbKS).
[issue2](https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&id=asyncapi_generator&open=AZB4sejVgviDxNeZYbKT).
[issue3](https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&id=asyncapi_generator&open=AZB4sejVgviDxNeZYbKU).

### CODE REVIEW

**Review by Gmin2 — APPROVED** [review]
LGTM

**Review by DhairyaMajmudar — APPROVED** [review]
Working correct 👍🏻

**Comment by derberg** [comment]
please adjust the title of the PR, look at the previous PR titles, and how they were adjusted by me - this will give you an idea how to make it better here

**Comment by rishabhr4** [comment]
> please adjust the title of the PR, look at the previous PR titles, and how they were adjusted by me - this will give you an idea how to make it better here

done cc @derberg thanks for the help

**Review by derberg — APPROVED** [review]

**Pull request merged**
