### PR TITLE
ci: minor fix in update docs workflow

### PR DESCRIPTION
**Pull request by DhairyaMajmudar**
**Description**
Fixed the path to generator docs at line 42

**Related issue(s)**
related to https://github.com/asyncapi/generator/issues/1264#issuecomment-2337884477

### CODE REVIEW

**Comment by DhairyaMajmudar** [comment]
cc: @derberg

**Review by derberg — COMMENTED** [review]
can you please also add another path to paths list in line 7

`.github/workflows/update-docs-in-website.yml`

so the workflow runs not only when docs are changed but also when workflow is updated?

**Comment by DhairyaMajmudar** [comment]
> can you please also add another path to paths list in line 7
> 
> `.github/workflows/update-docs-in-website.yml`
> 
> so the workflow runs not only when docs are changed but also when workflow is updated?

Sure thingy, I've updated my PR : )

**Review by derberg — APPROVED** [review]
Thanks again!

**Pull request merged**
