### PR TITLE
feat: introduce monorepo with filters package included

### PR DESCRIPTION
**Pull request by ayushnau**
Changes Added. 
1. Turborepo Added. 
2. Converted the generator repo to app,  inside the turborepo. 
3. Added the required scripts of the turborepo to the root package.json file. 

**Related issue(s)**

Resolves https://github.com/asyncapi/generator/issues/1044

### CODE REVIEW

**Review by derberg — COMMENTED** [review]
this PR is huge

can we introduce the change at least in 2 PRs? like first add `generator-filters` and then move `generator` to apps? cause now you just did moved all other files inside `apps/generator` but without checking if it makes sense, like for example all GitHub workflows

**Comment by ayushnau** [comment]
> this PR is huge
> 
> can we introduce the change at least in 2 PRs? like first add `generator-filters` and then move `generator` to apps? cause now you just did moved all other files inside `apps/generator` but without checking if it makes sense, like for example all GitHub workflows

@derberg should i convert the generator into turborepo. on its own. first . which means adding generator to the apps directory before as that would make sense.

**Comment by derberg** [comment]
@ayushnau yeah, I know they will be big, we just need to figure some approach maybe that can show that new files that are added are not modified or something like that, so review is smooth

but yeah, in this particular PR I know that if you split in 2 it will be big anyway, but seeing you moving GH actions workflows inside apps made me think we need to do one app at a time

**Comment by ayushnau** [comment]
> @ayushnau yeah, I know they will be big, we just need to figure some approach maybe that can show that new files that are added are not modified or something like that, so review is smooth
> 
> but yeah, in this particular PR I know that if you split in 2 it will be big anyway, but seeing you moving GH actions workflows inside apps made me think we need to do one app at a time

1. I think we can check by default in git which are only moved files
image

2. Actually I did removed the .github file but somehow the .github file changes didnt get added in the git changes.

**Review by derberg — COMMENTED** [review]
- `apps/generator/.all-contributorsrc` must stay in the root
- same sonar clound properties config - should be one for all apps
- same eslint and editor config files right?
- same files like codeowners or code of conduct, license, contri guide
- same readme banner
- also readme seems to be duplicated

**Comment by ayushnau** [comment]
> * `apps/generator/.all-contributorsrc` must stay in the root
> 
>     * same sonar clound properties config - should be one for all apps
> 
>     * same eslint and editor config files right?
> 
>     * same files like codeowners or code of conduct, license, contri guide
> 
>     * same readme banner
> 
>     * also readme seems to be duplicated

1. Ok and what about .editorConfig file. that also needs to be in root.

**Comment by AyushNautiyalDeveloper** [comment]
@derberg for running docker command will i need any credentials. as I am unable to run the command.

**Comment by ayushnau** [comment]
Acutually i was not able to get the changes in my branch. so need to refork it.

**Pull request closed without merging**
