### PR TITLE
fix: prevent potential memory leak by properly removing watcher references

### PR DESCRIPTION
**Pull request by Aryan4884**
**Description**

This PR addresses a potential memory leak issue in the Watcher class. When a watcher is closed, the reference to the watcher was previously set to null but not removed from the this.watchers object. Over time, this could lead to unnecessary memory consumption/memory leak.

### CODE REVIEW

**Review by DhairyaMajmudar — COMMENTED** [review]
There seems to be some unwanted formating changes which can further cause format workflow failure, can you pls. remove them by running the script `npm run lint:fix`

**Comment by Aryan4884** [comment]
@DhairyaMajmudar I have removed the extra formatting changes.

**Comment by derberg** [comment]
was this an issue coming from sonarcloud? of yes, please indicate it in description and provide to sonar report

**Comment by Aryan4884** [comment]
No, it is just an observational fix.

**Review by derberg — CHANGES_REQUESTED** [review]
ok, then I will close this issue, watcher is used in CLI only and we will deprecate it in few days and it doesn't make sense to invest in any changes to it

**Pull request closed without merging**
