### PR TITLE
test: support testing on windows with unixify package

### PR DESCRIPTION
**Pull request by derberg**
**Description**

- support testing on windows with unixify package
- silent linebreak linting

**Related issue(s)**
See also https://github.com/asyncapi/generator/pull/495/checks?check_run_id=1832629827

### CODE REVIEW

**Comment by jonaslagoni** [comment]
@derberg are you having fun 👽

**Comment by derberg** [comment]
@jonaslagoni seriously, I mean like seriously you are just sitting there with 🍺 and 🍿 and watching me bleeding? 😆

**Comment by derberg** [comment]
@jonaslagoni 

fuck yeah
Screenshot 2021-02-04 at 20 15 48

**Comment by derberg** [comment]
@jonaslagoni since you are around, how about approve? 😄

**Review by jonaslagoni — APPROVED** [review]
🦅

**Pull request merged**
