### PR TITLE
fix: corrected the relative paths

### PR DESCRIPTION
**Pull request by Aryan4884**
Issue #1294

### CODE REVIEW

**Review by Gmin2 — COMMENTED** [review]
Fix all the relative paths

**Comment by Aryan4884** [comment]
@Gmin2 Done

**Comment by derberg** [comment]
@Gmin2 please look into my comment from https://github.com/asyncapi/generator/issues/1294

**Review by derberg — COMMENTED** [review]
I have to close this PR, sorry - please follow discussion from https://github.com/asyncapi/generator/issues/1294 where we conclude first what has to be fixed

**Pull request closed without merging**
