### PR TITLE
fix: updated typescript & ts-node versions to the latest ones

### PR DESCRIPTION
**Pull request by flamewow**
**Related issue(s)**

Resolves [#841 ](https://github.com/asyncapi/generator/issues/841)

### CODE REVIEW

**Comment by derberg** [comment]
@flamewow please update to `fix: ` the PR title, otherwise release will not be triggered, and the patch not released. We need to do a release if we update prod deps.

**Comment by ChronicStone** [comment]
Hi @derberg, is there anything left to co we can help with to have this PR merged ?

**Review by derberg — APPROVED** [review]
@ChronicStone no, ready to merge. I was just giving time to other maintainers to have a look.

**Pull request merged**
