### PR TITLE
refactor: added a statement for sort operation

### PR DESCRIPTION
**Pull request by kanumalivad**
**Related issue(s)**
#667

### CODE REVIEW

**Comment by magicmatatjahu** [comment]
@kanumalivad Hi! Thanks for contribution! Unfortunately you have still code smell - https://sonarcloud.io/project/issues?id=asyncapi_generator&open=AXw6OsbhiXOsm5cm9b-w&pullRequest=669&resolved=false&types=CODE_SMELL

I suggest you to return sorted array immediately from function without local variables, something like:

```js
return Object.keys(configParams).map(param => [levenshtein(wrongParam, param), param]).sort(sortInt)[0][1];
```

**Review by magicmatatjahu — CHANGES_REQUESTED** [review]
@kanumalivad Hi! Thanks for contribution! Unfortunately you have still code smell - https://sonarcloud.io/project/issues?id=asyncapi_generator&open=AXw6OsbhiXOsm5cm9b-w&pullRequest=669&resolved=false&types=CODE_SMELL

I suggest you to return sorted array immediately from function without local variables, something like:

```js
return Object.keys(configParams).map(param => [levenshtein(wrongParam, param), param]).sort(sortInt)[0][1];
```

**Comment by kanumalivad** [comment]
@magicmatatjahu Thank you so much for suggestion.

**Review by magicmatatjahu — APPROVED** [review]

**Comment by magicmatatjahu** [comment]
@kanumalivad Thanks for contribution!

**Pull request merged**
