### PR TITLE
chore: update multi-parser to last version

### PR DESCRIPTION
**Pull request by smoya**
**Description**

This PR updates `@smoya/multi-parser` to last version (`4.0.0`).

### CODE REVIEW

**Review by jonaslagoni — DISMISSED** [review]

**Comment by derberg** [comment]
@smoya not so fast 😄 tests are failing

**Comment by smoya** [comment]
> @smoya not so fast 😄 tests are failing



Fixed now!

**Review by jonaslagoni — APPROVED** [review]

**Pull request merged**
