### PR TITLE
fix: upgrade dependencies

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This PR updates most dependencies to address most of the https://github.com/asyncapi/generator/security/dependabot issues.

Jest changes:
- Renamed `genMockFromModule` to `createMockFromModule` -> https://jestjs.io/docs/jest-object#jestcreatemockfrommodulemodulename

**Related issue(s)**
Fixes https://github.com/asyncapi/generator/security/advisories/GHSA-9x5f-xcwh-x6pg

### CODE REVIEW

**Comment by jonaslagoni** [comment]
Still WIP, need to figure out why the test setup no longer works for the new version of Jest.

**Comment by jonaslagoni** [comment]
When I use the Jest Test explorer in VSCode the tests work as expected 🤔

**Comment by jonaslagoni** [comment]
@derberg do you have any idea as to what might not be working?

**Comment by derberg** [comment]
@jonaslagoni dunno, too many updates in one PR. I can only see it is related to unit tests, not integration tests 🤷🏼 

I recommend to not make changes to `devDependencies` as we do not really care about their security issues right?

**Pull request closed without merging**
