### PR TITLE
docs: fix broken hyperlinks in generator docs

### PR DESCRIPTION
**Pull request by kakabisht**
Refer: https://github.com/asyncapi/generator/issues/935

### CODE REVIEW

**Comment by Florence-Njeri** [comment]
> We require all PRs to follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/). More details 👇🏼
> 
> ```
>  No release type found in pull request title "fix the broken hyperlinks in generator docs". Add a prefix to indicate what kind of release this pull request corresponds to. For reference, see https://www.conventionalcommits.org/
> 
> Available types:
>  - feat: A new feature
>  - fix: A bug fix
>  - docs: Documentation only changes
>  - style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
>  - refactor: A code change that neither fixes a bug nor adds a feature
>  - perf: A code change that improves performance
>  - test: Adding missing tests or correcting existing tests
>  - build: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
>  - ci: Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
>  - chore: Other changes that don't modify src or test files
>  - revert: Reverts a previous commit
> ```

@kakabisht please go through the PR-creating format we use as suggested by the bot and update your pr title accordingly

**Comment by derberg** [comment]
@Florence-Njeri I updated the PR title. As far as I see looks like PR makes sense. There are many additional formatting changes that are not related to PR, but yeah, the links are fixed

**Comment by derberg** [comment]
@Florence-Njeri can you have a look?

**Review by derberg — APPROVED** [review]

**Review by Florence-Njeri — APPROVED** [review]

**Pull request merged**
