### PR TITLE
Fixed the issue with some channels might not have tags

### LINKED ISSUE #112: No need to Untagged section when byTags is true
image

If there aren't untagged routes, no need for the untagged menu section.

Thank you for working on this project. Let me know if I can pitch in to get this issue and the other one I filed taken care of.

### LINKED ISSUE #141: Template render error using byTags sidebarOrganization
ag asyncapi.yaml html --param sidebarOrganization=byTags
```
Something went wrong:
Template render error: (unknown path)
  Template render error: (/usr/local/lib/node_modules/asyncapi-generator/templates/html/.partials/sidebar.html)
  Error: Unable to call `the return value of (the return value of (channel["subscribe"])["tags"])["0"]["name"]`, which is undefined or falsey
    at Object._prettifyError (/usr/local/lib/node_modules/asyncapi-generator/node_modules/nunjucks/src/lib.js:36:11)
    at /usr/local/lib/node_modules/asyncapi-generator/node_modules/nunjucks/src/environment.js:567:19
    at eval (eval at _compile (/usr/local/lib/node_modules/asyncapi-generator/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:24:11)
    at /usr/local/lib/node_modules/asyncapi-generator/node_modules/nunjucks/src/environment.js:575:11
    at eval (eval at _compile (/usr/local/lib/node_modules/asyncapi-generator/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:12:11)
    at /usr/local/lib/node_modules/asyncapi-generator/node_modules/nunjucks/src/environment.js:617:9
    at Template.root [as rootRenderFunc] (eval at _compile (/usr/local/lib/node_modules/asyncapi-generator/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:63:3)
    at Template.getExported (/usr/local/lib/node_modules/asyncapi-generator/node_modules/nunjucks/src/environment.js:615:10)
    at eval (eval at _compile (/usr/local/lib/node_modules/asyncapi-generator/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:11:5)
    at createTemplate (/usr/local/lib/node_modules/asyncapi-generator/node_modules/nunjucks/src/environment.js:315:9)
```

Any ideas what is going wrong?

### LINKED ISSUE #148: html template using byTags sidebarOrganization does not look through all the tags
While solving #141 I saw that only the first tag are checked:
https://github.com/asyncapi/generator/blob/f1c196a8cb12a667d4dbae5b01af6b538ca184d9/templates/html/.partials/sidebar.html#L47
Meaning that if I define operations like:
```json
...
"tags": [{
	"name": "user1",
	"description": "User-related messages"
},
{
	"name": "user",
	"description": "User-related messages"
}
],
...
```
and the tags like:
```json
...
"tags": [
{
	"name": "user",
	"description": "User-related messages"
}
],
...
```
the operation would not be listed under the tags, guess this is not intended?

### PR DESCRIPTION
**Pull request by jonaslagoni**
Fixes #141
Fixes #148
Fixes #112

### CODE REVIEW

**Comment by jonaslagoni** [comment]
If #148 is an issue I will include it in this PR. Should not have asked a review just yet :smile:

**Comment by jonaslagoni** [comment]
Also fixed #112

**Comment by fmvilas** [comment]
I've edited your PR description so it has "Fixes #issuenumber". FYI, if you write it this way, Github will automatically close the issues once this PR is merged. Plus, if you go to the issues, you'll see the text "May be fixed by #147" under the title :)

**Comment by fmvilas** [comment]
BTW @jonaslagoni, are you on AsyncAPI Slack? Feel free to join us: [asyncapi.com/slack-invite](https://www.asyncapi.com/slack-invite).

**Pull request merged**
