### PR TITLE
docs: update links referring to configuration file

### LINKED ISSUE #941: [📑 Docs]: update the hyperlink in hooks.md
### What Dev Docs changes are you proposing?

Hyperlink Not working, I would like to fix this issue in this doc.- [read more about the configuration file](https://www.asyncapi.com/docs/tools/generator/hooks#configuration-file).

[https://www.asyncapi.com/docs/tools/generator/hooks#configuration-file](https://github.com/asyncapi/website/issues/url)

Original issue: asyncapi/website#1542
credits: @golu-99

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by AnimeshKumar923**
**Description**

- This PR addressed the issue faced in the hooks.md page of the docs section in the main website
- Hyperlink: https://www.asyncapi.com/docs/tools/generator/hooks 

**Related issue(s)**
Resolves #941

### CODE REVIEW

**Comment by AnimeshKumar923** [comment]
generator-broken-links

2 hyperlinks named with `_read more about the configuration file_` are to be fixed

**Review by pratik2315 — APPROVED** [review]
LGTM

**Review by Florence-Njeri — APPROVED** [review]

**Comment by AnimeshKumar923** [comment]
Any updates? @Florence-Njeri @pratik2315

**Comment by derberg** [comment]
rerunning failed jobs

@Florence-Njeri @pratik2315 feel free to merge once CI gets green

**Pull request merged**
