### PR TITLE
docs(dummy): add specification extensions

### LINKED ISSUE #535: Add specification extensions sample in the dummy.yml
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
The generated html doc not showing the specification extension block
- How will this change help?
Show how it is rendering
- What is the motivation?
Trying to work on the bindinds display, i'm not able to easily see how the actual  specification extension block works

#### Description
Please try answering few of those questions
- What changes have to be introduced?
just few extensions in the dummy specification to illustration primitive, object and array type
- Will this be a breaking change?
- no
- How could it be implemented/designed?

### PR DESCRIPTION
**Pull request by M3lkior**
Add some specification extensions samples to illustrate the extension rendering

Close #535

Here is the result : 
image

### CODE REVIEW

**Review by derberg — DISMISSED** [review]

**Comment by derberg** [comment]
@M3lkior you will need to update the test snapshot so it contains those new properties

**Comment by M3lkior** [comment]
> @M3lkior you will need to update the test snapshot so it contains those new properties

Hum ; it seems hard to maintain and apparently other missing HTML block are missing in the snapshot test from previous dummy evolution

Example: 
image

**Comment by derberg** [comment]
@M3lkior what changed in the UI of generated HTML after you added the extensions to dummy example. Did you try manually? afaik extensions are "expandable" which means the svg button for expand/collapse must be added, or?

**Comment by M3lkior** [comment]
> @M3lkior what changed in the UI of generated HTML after you added the extensions to dummy example. Did you try manually? afaik extensions are "expandable" which means the svg button for expand/collapse must be added, or?

yes this is like my screenshot above.

I'm not familiar with Jest Snapshot but i will try to fix the tests

**Comment by derberg** [comment]
snapshot is basically a copy of whatever you snapshot (js, HTML, css, whatever text file), so in case of this test, we generate HTML template and "copy" it and store initial HTML, and then in test we compare newly generated HTML against stored snapshot. When you add something to the dummy spec it basically means the the output of HTML template also changes, and test fails, so you just need to update the snapshot. IDE should give you an option to automatically do it, like update snapshot, if you have jest plugin I guess. Other solution is to do it manually, or just remove current snapshot and let tests generate it from scratch

**Comment by M3lkior** [comment]
> snapshot is basically a copy of whatever you snapshot (js, HTML, css, whatever text file), so in case of this test, we generate HTML template and "copy" it and store initial HTML, and then in test we compare newly generated HTML against stored snapshot. When you add something to the dummy spec it basically means the the output of HTML template also changes, and test fails, so you just need to update the snapshot. IDE should give you an option to automatically do it, like update snapshot, if you have jest plugin I guess. Other solution is to do it manually, or just remove current snapshot and let tests generate it from scratch

done @derberg  🤟

**Review by derberg — APPROVED** [review]

**Pull request merged**
