### PR TITLE
refactor: optional chaining instead of expression in `parser.js`

### PR DESCRIPTION
**Pull request by rishabhr4**
Description
refactored apps/generator/lib/parser.js mentioned in this [issue](https://sonarcloud.io/project/issues?fileUuids=AZB4seZIgviDxNeZYbJz&issueStatuses=OPEN%2CCONFIRMED&id=asyncapi_generator&open=AZB4sej0gviDxNeZYbKi&tab=code)

Changes Made-
used optional chaining to maintain readability.

### CODE REVIEW

**Review by Gmin2 — COMMENTED** [review]
make the PR title `refactor: used optional chainining instead of expression `, jus a whitespace that is causing the action to fail

other then that LGTM

**Comment by rishabhr4** [comment]
> make the PR title `refactor: used optional chainining instead of expression `, jus a whitespace that is causing the action to fail
> 
> other then that LGTM

done cc @Gmin2

**Review by derberg — APPROVED** [review]

**Comment by derberg** [comment]
failing test

**Comment by DhairyaMajmudar** [comment]
@rishabhr4 seems like your linting test is failing, pls. run the command `npm run lint` and push the changes into PR : )

**Comment by rishabhr4** [comment]
> @rishabhr4 seems like your linting test is failing, pls. run the command `npm run lint` and push the changes into PR : )
Hi @DhairyaMajmudar thanks for the help , i tried to fix it please let me know if it it correct

**Comment by DhairyaMajmudar** [comment]
> > @rishabhr4 seems like your linting test is failing, pls. run the command `npm run lint` and push the changes into PR : )
> > Hi @DhairyaMajmudar thanks for the help , i tried to fix it please let me know if it it correct

Yeah, tests are now passing, amazing!!

**Comment by Gmin2** [comment]
> Yeah, tests are now passing, amazing!!

Test are not being run yet

**Comment by derberg** [comment]
@rishabhr4 can you explain why change in eslint was needed

**Comment by derberg** [comment]
forget my question about eslint

**Pull request merged**
