### PR TITLE
refactor: use an object spread instead of `Object.assign` in filters

### PR DESCRIPTION
**Pull request by rishabhr4**
Description
refactored apps/nunjucks-filters/src/index.js mentioned in this [issue](https://sonarcloud.io/project/issues?languages=js&issueStatuses=OPEN%2CCONFIRMED&id=asyncapi_generator&open=AZD-TPs2DKL_zKkK1XuA)

Changes Made
Removed object assign and used object spread

related https://github.com/asyncapi/generator/issues/1272

### CODE REVIEW

**Review by Gmin2 — APPROVED** [review]
LGTM

**Comment by derberg** [comment]
@Gmin2 thanks for helping with review

**Comment by derberg** [comment]
tests are failing, linter - to be more precise

**Comment by rishabhr4** [comment]
> tests are failing, linter - to be more precise

sorry 
i have now ran the tests and fixed it

**Review by derberg — APPROVED** [review]
lgtm

**Pull request merged**
