### PR TITLE
refactor: switch to optional chaining in custom filters and update eslint config

### PR DESCRIPTION
**Pull request by rishabhr4**
Description
This pull request addresses the issue of unnecessary escape characters in the code.

Changes Made
Removed unnecessary escape characters (\$) from the fileName.replace statement:

### CODE REVIEW

**Comment by Gmin2** [comment]
please also include the sonarcloud error that this PR target to solve, thanks

**Comment by rishabhr4** [comment]
> Description This pull request addresses the issue of unnecessary escape characters in the code.
> 
> Changes Made Removed unnecessary escape characters ($) from the fileName.replace statement:

This PR resolves this [issue](https://sonarcloud.io/project/issues?languages=js&issueStatuses=OPEN%2CCONFIRMED&id=asyncapi_generator&open=AZB4sejpgviDxNeZYbKZ).

**Review by derberg — COMMENTED** [review]
please remove changes from `apps/generator/lib/generator.js` as I don't think we have that covered with tests, and some more work will be needed - so yeah, let us not mix the scope, please add separate PR for that

**Comment by derberg** [comment]
@rishabhr4 please react to failing test run

**Comment by rishabhr4** [comment]
> @rishabhr4 please react to failing test run

Done cc @derberg

**Comment by derberg** [comment]
what was the reason for changing eslint config?

**Comment by derberg** [comment]
ok, nevermind I figured it needs an update as old linter did not support optional chaining

**Comment by rishabhr4** [comment]
> ok, nevermind I figured it needs an update as old linter did not support optional chaining

yeah that's why linter tests were failing

**Pull request merged**
