### PR TITLE
docs: update template-development.md

### PR DESCRIPTION
**Pull request by nickshoe**
**Description**

- Fix package.json "supportedProtocols" examples (use a list of values instead of a string)
- Restate the "template" folder explanation

### CODE REVIEW

**Comment by Florence-Njeri** [comment]
Hi @nickshoe. Thank you for helping make the Generator documentation better. What issue is this PR addressing?

**Comment by nickshoe** [comment]
Hi @Florence-Njeri there is not a tracked issue, the PR addresses a problem in the package.json example and (hopefully) clarifies the purpouse of the template folder and of its content.

**Comment by nickshoe** [comment]
Hey @Florence-Njeri, let me know if I shall change something or create an issue for this PR. ;)

**Comment by derberg** [comment]
@Florence-Njeri fyi we do not make it mandatory for people to create issue first if the PR has a small scope. In this case of `supportedProtocols` the fix makes total sense. Regarding wording change for other parts, I leave it up to you to decide

**Comment by Florence-Njeri** [comment]
> @Florence-Njeri fyi we do not make it mandatory for people to create issue first if the PR has a small scope. In this case of `supportedProtocols` the fix makes total sense. Regarding wording change for other parts, I leave it up to you to decide

Makes sense

**Comment by derberg** [comment]
@Florence-Njeri can you have a look?

**Review by derberg — APPROVED** [review]

**Comment by derberg** [comment]
@Florence-Njeri @pratik2315 folks we need your approval to merge

**Comment by Florence-Njeri** [comment]
@derberg @nickshoe I left one suggestion on the file, please take a look and accept if it looks good

**Review by Florence-Njeri — APPROVED** [review]

**Pull request merged**
